//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://www.his.bg}sequence" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}asNeeded" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}route"/&gt;
 *         &lt;element ref="{https://www.his.bg}doseQuantity"/&gt;
 *         &lt;element ref="{https://www.his.bg}frequency"/&gt;
 *         &lt;element ref="{https://www.his.bg}period"/&gt;
 *         &lt;element ref="{https://www.his.bg}periodUnit"/&gt;
 *         &lt;element ref="{https://www.his.bg}boundsDuration"/&gt;
 *         &lt;element ref="{https://www.his.bg}boundsDurationUnit"/&gt;
 *         &lt;element ref="{https://www.his.bg}text" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sequence",
    "asNeeded",
    "route",
    "doseQuantity",
    "frequency",
    "period",
    "periodUnit",
    "boundsDuration",
    "boundsDurationUnit",
    "text"
})
@XmlRootElement(name = "dosageInstruction")
public class DosageInstruction {

    protected P004_SequenceBase sequence;
    protected P004_AsNeededBase asNeeded;
    @XmlElement(required = true)
    protected P004_RouteBase route;
    @XmlElement(required = true)
    protected P004_DoseQuantityBase doseQuantity;
    @XmlElement(required = true)
    protected P004_FrequencyBase frequency;
    @XmlElement(required = true)
    protected P004_PeriodBase period;
    @XmlElement(required = true)
    protected P004_PeriodUnitBase periodUnit;
    @XmlElement(required = true)
    protected P004_BoundsDurationBase boundsDuration;
    @XmlElement(required = true)
    protected P004_BoundsDurationUnitBase boundsDurationUnit;
    protected P004_TextBase text;

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link P004_SequenceBase }
     *     
     */
    public P004_SequenceBase getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_SequenceBase }
     *     
     */
    public void setSequence(P004_SequenceBase value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the asNeeded property.
     * 
     * @return
     *     possible object is
     *     {@link P004_AsNeededBase }
     *     
     */
    public P004_AsNeededBase getAsNeeded() {
        return asNeeded;
    }

    /**
     * Sets the value of the asNeeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_AsNeededBase }
     *     
     */
    public void setAsNeeded(P004_AsNeededBase value) {
        this.asNeeded = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link P004_RouteBase }
     *     
     */
    public P004_RouteBase getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_RouteBase }
     *     
     */
    public void setRoute(P004_RouteBase value) {
        this.route = value;
    }

    /**
     * Gets the value of the doseQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link P004_DoseQuantityBase }
     *     
     */
    public P004_DoseQuantityBase getDoseQuantity() {
        return doseQuantity;
    }

    /**
     * Sets the value of the doseQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_DoseQuantityBase }
     *     
     */
    public void setDoseQuantity(P004_DoseQuantityBase value) {
        this.doseQuantity = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link P004_FrequencyBase }
     *     
     */
    public P004_FrequencyBase getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_FrequencyBase }
     *     
     */
    public void setFrequency(P004_FrequencyBase value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link P004_PeriodBase }
     *     
     */
    public P004_PeriodBase getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_PeriodBase }
     *     
     */
    public void setPeriod(P004_PeriodBase value) {
        this.period = value;
    }

    /**
     * Gets the value of the periodUnit property.
     * 
     * @return
     *     possible object is
     *     {@link P004_PeriodUnitBase }
     *     
     */
    public P004_PeriodUnitBase getPeriodUnit() {
        return periodUnit;
    }

    /**
     * Sets the value of the periodUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_PeriodUnitBase }
     *     
     */
    public void setPeriodUnit(P004_PeriodUnitBase value) {
        this.periodUnit = value;
    }

    /**
     * Gets the value of the boundsDuration property.
     * 
     * @return
     *     possible object is
     *     {@link P004_BoundsDurationBase }
     *     
     */
    public P004_BoundsDurationBase getBoundsDuration() {
        return boundsDuration;
    }

    /**
     * Sets the value of the boundsDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_BoundsDurationBase }
     *     
     */
    public void setBoundsDuration(P004_BoundsDurationBase value) {
        this.boundsDuration = value;
    }

    /**
     * Gets the value of the boundsDurationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link P004_BoundsDurationUnitBase }
     *     
     */
    public P004_BoundsDurationUnitBase getBoundsDurationUnit() {
        return boundsDurationUnit;
    }

    /**
     * Sets the value of the boundsDurationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_BoundsDurationUnitBase }
     *     
     */
    public void setBoundsDurationUnit(P004_BoundsDurationUnitBase value) {
        this.boundsDurationUnit = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link P004_TextBase }
     *     
     */
    public P004_TextBase getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_TextBase }
     *     
     */
    public void setText(P004_TextBase value) {
        this.text = value;
    }

}
