//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://www.his.bg}sender"/&gt;
 *         &lt;element ref="{https://www.his.bg}senderId"/&gt;
 *         &lt;element ref="{https://www.his.bg}recipient"/&gt;
 *         &lt;element ref="{https://www.his.bg}recipientId"/&gt;
 *         &lt;element ref="{https://www.his.bg}messageId"/&gt;
 *         &lt;element ref="{https://www.his.bg}messageType"/&gt;
 *         &lt;element ref="{https://www.his.bg}createdOn"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sender",
    "senderId",
    "recipient",
    "recipientId",
    "messageId",
    "messageType",
    "createdOn"
})
@XmlRootElement(name = "header")
public class Header {

    @XmlElement(required = true)
    protected Sender sender;
    @XmlElement(required = true)
    protected SenderId senderId;
    @XmlElement(required = true)
    protected Recipient recipient;
    @XmlElement(required = true)
    protected RecipientId recipientId;
    @XmlElement(required = true)
    protected MessageId messageId;
    @XmlElement(required = true)
    protected MessageType messageType;
    @XmlElement(required = true)
    protected CreatedOn createdOn;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link Sender }
     *     
     */
    public Sender getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sender }
     *     
     */
    public void setSender(Sender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the senderId property.
     * 
     * @return
     *     possible object is
     *     {@link SenderId }
     *     
     */
    public SenderId getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderId }
     *     
     */
    public void setSenderId(SenderId value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link Recipient }
     *     
     */
    public Recipient getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recipient }
     *     
     */
    public void setRecipient(Recipient value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the recipientId property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientId }
     *     
     */
    public RecipientId getRecipientId() {
        return recipientId;
    }

    /**
     * Sets the value of the recipientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientId }
     *     
     */
    public void setRecipientId(RecipientId value) {
        this.recipientId = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link MessageId }
     *     
     */
    public MessageId getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageId }
     *     
     */
    public void setMessageId(MessageId value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link MessageType }
     *     
     */
    public MessageType getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageType }
     *     
     */
    public void setMessageType(MessageType value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the createdOn property.
     * 
     * @return
     *     possible object is
     *     {@link CreatedOn }
     *     
     */
    public CreatedOn getCreatedOn() {
        return createdOn;
    }

    /**
     * Sets the value of the createdOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreatedOn }
     *     
     */
    public void setCreatedOn(CreatedOn value) {
        this.createdOn = value;
    }

}
