//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p004;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://www.his.bg}sequenceId"/&gt;
 *         &lt;element ref="{https://www.his.bg}medicationCode"/&gt;
 *         &lt;element ref="{https://www.his.bg}priority" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}mkb" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}nhifCode" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}quantity"/&gt;
 *         &lt;element ref="{https://www.his.bg}quantityDispensed" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}isDispensed" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}isSubstitutionAllowed" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}dosageInstruction" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sequenceId",
    "medicationCode",
    "priority",
    "mkb",
    "nhifCode",
    "quantity",
    "quantityDispensed",
    "isDispensed",
    "isSubstitutionAllowed",
    "dosageInstruction"
})
@XmlRootElement(name = "medication")
public class Medication {

    @XmlElement(required = true)
    protected P004_SequenceIdBase sequenceId;
    @XmlElement(required = true)
    protected P004_MedicationCodeBase medicationCode;
    protected P004_PriorityBase priority;
    protected P004_MkbBase mkb;
    protected P004_NhifCodeBase nhifCode;
    @XmlElement(required = true)
    protected P004_QuantityBase quantity;
    protected P004_QuantityDispensedBase quantityDispensed;
    protected P004_IsDispensedBase isDispensed;
    protected P004_IsSubstitutionAllowedBase isSubstitutionAllowed;
    @XmlElement(required = true)
    protected List<DosageInstruction> dosageInstruction;

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link P004_SequenceIdBase }
     *     
     */
    public P004_SequenceIdBase getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_SequenceIdBase }
     *     
     */
    public void setSequenceId(P004_SequenceIdBase value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the medicationCode property.
     * 
     * @return
     *     possible object is
     *     {@link P004_MedicationCodeBase }
     *     
     */
    public P004_MedicationCodeBase getMedicationCode() {
        return medicationCode;
    }

    /**
     * Sets the value of the medicationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_MedicationCodeBase }
     *     
     */
    public void setMedicationCode(P004_MedicationCodeBase value) {
        this.medicationCode = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link P004_PriorityBase }
     *     
     */
    public P004_PriorityBase getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_PriorityBase }
     *     
     */
    public void setPriority(P004_PriorityBase value) {
        this.priority = value;
    }

    /**
     * Gets the value of the mkb property.
     * 
     * @return
     *     possible object is
     *     {@link P004_MkbBase }
     *     
     */
    public P004_MkbBase getMkb() {
        return mkb;
    }

    /**
     * Sets the value of the mkb property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_MkbBase }
     *     
     */
    public void setMkb(P004_MkbBase value) {
        this.mkb = value;
    }

    /**
     * Gets the value of the nhifCode property.
     * 
     * @return
     *     possible object is
     *     {@link P004_NhifCodeBase }
     *     
     */
    public P004_NhifCodeBase getNhifCode() {
        return nhifCode;
    }

    /**
     * Sets the value of the nhifCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_NhifCodeBase }
     *     
     */
    public void setNhifCode(P004_NhifCodeBase value) {
        this.nhifCode = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link P004_QuantityBase }
     *     
     */
    public P004_QuantityBase getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_QuantityBase }
     *     
     */
    public void setQuantity(P004_QuantityBase value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the quantityDispensed property.
     * 
     * @return
     *     possible object is
     *     {@link P004_QuantityDispensedBase }
     *     
     */
    public P004_QuantityDispensedBase getQuantityDispensed() {
        return quantityDispensed;
    }

    /**
     * Sets the value of the quantityDispensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_QuantityDispensedBase }
     *     
     */
    public void setQuantityDispensed(P004_QuantityDispensedBase value) {
        this.quantityDispensed = value;
    }

    /**
     * Gets the value of the isDispensed property.
     * 
     * @return
     *     possible object is
     *     {@link P004_IsDispensedBase }
     *     
     */
    public P004_IsDispensedBase getIsDispensed() {
        return isDispensed;
    }

    /**
     * Sets the value of the isDispensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_IsDispensedBase }
     *     
     */
    public void setIsDispensed(P004_IsDispensedBase value) {
        this.isDispensed = value;
    }

    /**
     * Gets the value of the isSubstitutionAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link P004_IsSubstitutionAllowedBase }
     *     
     */
    public P004_IsSubstitutionAllowedBase getIsSubstitutionAllowed() {
        return isSubstitutionAllowed;
    }

    /**
     * Sets the value of the isSubstitutionAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_IsSubstitutionAllowedBase }
     *     
     */
    public void setIsSubstitutionAllowed(P004_IsSubstitutionAllowedBase value) {
        this.isSubstitutionAllowed = value;
    }

    /**
     * Gets the value of the dosageInstruction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dosageInstruction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDosageInstruction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DosageInstruction }
     * 
     * 
     */
    public List<DosageInstruction> getDosageInstruction() {
        if (dosageInstruction == null) {
            dosageInstruction = new ArrayList<DosageInstruction>();
        }
        return this.dosageInstruction;
    }

}
