//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p004;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.eprescription.model.p004 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Contents_QNAME = new QName("https://www.his.bg", "contents");
    private final static QName _Signature_QNAME = new QName("https://www.his.bg", "signature");
    private final static QName _Message_QNAME = new QName("https://www.his.bg", "message");
    private final static QName _Sequence_QNAME = new QName("https://www.his.bg", "sequence");
    private final static QName _AsNeeded_QNAME = new QName("https://www.his.bg", "asNeeded");
    private final static QName _Route_QNAME = new QName("https://www.his.bg", "route");
    private final static QName _DoseQuantity_QNAME = new QName("https://www.his.bg", "doseQuantity");
    private final static QName _Frequency_QNAME = new QName("https://www.his.bg", "frequency");
    private final static QName _Period_QNAME = new QName("https://www.his.bg", "period");
    private final static QName _PeriodUnit_QNAME = new QName("https://www.his.bg", "periodUnit");
    private final static QName _BoundsDuration_QNAME = new QName("https://www.his.bg", "boundsDuration");
    private final static QName _BoundsDurationUnit_QNAME = new QName("https://www.his.bg", "boundsDurationUnit");
    private final static QName _Text_QNAME = new QName("https://www.his.bg", "text");
    private final static QName _SequenceId_QNAME = new QName("https://www.his.bg", "sequenceId");
    private final static QName _MedicationCode_QNAME = new QName("https://www.his.bg", "medicationCode");
    private final static QName _Priority_QNAME = new QName("https://www.his.bg", "priority");
    private final static QName _Mkb_QNAME = new QName("https://www.his.bg", "mkb");
    private final static QName _NhifCode_QNAME = new QName("https://www.his.bg", "nhifCode");
    private final static QName _Quantity_QNAME = new QName("https://www.his.bg", "quantity");
    private final static QName _QuantityDispensed_QNAME = new QName("https://www.his.bg", "quantityDispensed");
    private final static QName _IsDispensed_QNAME = new QName("https://www.his.bg", "isDispensed");
    private final static QName _IsSubstitutionAllowed_QNAME = new QName("https://www.his.bg", "isSubstitutionAllowed");
    private final static QName _GroupIdentifier_QNAME = new QName("https://www.his.bg", "groupIdentifier");
    private final static QName _NrnPrescription_QNAME = new QName("https://www.his.bg", "nrnPrescription");
    private final static QName _Lrn_QNAME = new QName("https://www.his.bg", "lrn");
    private final static QName _Status_QNAME = new QName("https://www.his.bg", "status");
    private final static QName _AuthoredOn_QNAME = new QName("https://www.his.bg", "authoredOn");
    private final static QName _Category_QNAME = new QName("https://www.his.bg", "category");
    private final static QName _IsProtocolBased_QNAME = new QName("https://www.his.bg", "isProtocolBased");
    private final static QName _ProtocolNumber_QNAME = new QName("https://www.his.bg", "protocolNumber");
    private final static QName _ProtocolDate_QNAME = new QName("https://www.his.bg", "protocolDate");
    private final static QName _RhifNumber_QNAME = new QName("https://www.his.bg", "rhifNumber");
    private final static QName _BasedOn_QNAME = new QName("https://www.his.bg", "basedOn");
    private final static QName _DispensationType_QNAME = new QName("https://www.his.bg", "dispensationType");
    private final static QName _AllowedRepeatsNumber_QNAME = new QName("https://www.his.bg", "allowedRepeatsNumber");
    private final static QName _IsFulfilled_QNAME = new QName("https://www.his.bg", "isFulfilled");
    private final static QName _IdentifierType_QNAME = new QName("https://www.his.bg", "identifierType");
    private final static QName _Identifier_QNAME = new QName("https://www.his.bg", "identifier");
    private final static QName _BirthDate_QNAME = new QName("https://www.his.bg", "birthDate");
    private final static QName _Gender_QNAME = new QName("https://www.his.bg", "gender");
    private final static QName _Age_QNAME = new QName("https://www.his.bg", "age");
    private final static QName _Weight_QNAME = new QName("https://www.his.bg", "weight");
    private final static QName _IsPregnant_QNAME = new QName("https://www.his.bg", "isPregnant");
    private final static QName _IsBreastFeeding_QNAME = new QName("https://www.his.bg", "isBreastFeeding");
    private final static QName _PrBookNumber_QNAME = new QName("https://www.his.bg", "prBookNumber");
    private final static QName _Name_QNAME = new QName("https://www.his.bg", "name");
    private final static QName _Address_QNAME = new QName("https://www.his.bg", "address");
    private final static QName _Phone_QNAME = new QName("https://www.his.bg", "phone");
    private final static QName _Email_QNAME = new QName("https://www.his.bg", "email");
    private final static QName _Pmi_QNAME = new QName("https://www.his.bg", "pmi");
    private final static QName _Qualification_QNAME = new QName("https://www.his.bg", "qualification");
    private final static QName _PracticeNumber_QNAME = new QName("https://www.his.bg", "practiceNumber");
    private final static QName _NhifNumber_QNAME = new QName("https://www.his.bg", "nhifNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.eprescription.model.p004
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sender }
     * 
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link SenderId }
     * 
     */
    public SenderId createSenderId() {
        return new SenderId();
    }

    /**
     * Create an instance of {@link Recipient }
     * 
     */
    public Recipient createRecipient() {
        return new Recipient();
    }

    /**
     * Create an instance of {@link RecipientId }
     * 
     */
    public RecipientId createRecipientId() {
        return new RecipientId();
    }

    /**
     * Create an instance of {@link MessageId }
     * 
     */
    public MessageId createMessageId() {
        return new MessageId();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link CreatedOn }
     * 
     */
    public CreatedOn createCreatedOn() {
        return new CreatedOn();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link P004_ContentsBase }
     * 
     */
    public P004_ContentsBase createP004_ContentsBase() {
        return new P004_ContentsBase();
    }

    /**
     * Create an instance of {@link P004_MessageBase }
     * 
     */
    public P004_MessageBase createP004_MessageBase() {
        return new P004_MessageBase();
    }

    /**
     * Create an instance of {@link P004_SequenceBase }
     * 
     */
    public P004_SequenceBase createP004_SequenceBase() {
        return new P004_SequenceBase();
    }

    /**
     * Create an instance of {@link P004_AsNeededBase }
     * 
     */
    public P004_AsNeededBase createP004_AsNeededBase() {
        return new P004_AsNeededBase();
    }

    /**
     * Create an instance of {@link P004_RouteBase }
     * 
     */
    public P004_RouteBase createP004_RouteBase() {
        return new P004_RouteBase();
    }

    /**
     * Create an instance of {@link P004_DoseQuantityBase }
     * 
     */
    public P004_DoseQuantityBase createP004_DoseQuantityBase() {
        return new P004_DoseQuantityBase();
    }

    /**
     * Create an instance of {@link P004_FrequencyBase }
     * 
     */
    public P004_FrequencyBase createP004_FrequencyBase() {
        return new P004_FrequencyBase();
    }

    /**
     * Create an instance of {@link P004_PeriodBase }
     * 
     */
    public P004_PeriodBase createP004_PeriodBase() {
        return new P004_PeriodBase();
    }

    /**
     * Create an instance of {@link P004_PeriodUnitBase }
     * 
     */
    public P004_PeriodUnitBase createP004_PeriodUnitBase() {
        return new P004_PeriodUnitBase();
    }

    /**
     * Create an instance of {@link P004_BoundsDurationBase }
     * 
     */
    public P004_BoundsDurationBase createP004_BoundsDurationBase() {
        return new P004_BoundsDurationBase();
    }

    /**
     * Create an instance of {@link P004_BoundsDurationUnitBase }
     * 
     */
    public P004_BoundsDurationUnitBase createP004_BoundsDurationUnitBase() {
        return new P004_BoundsDurationUnitBase();
    }

    /**
     * Create an instance of {@link P004_TextBase }
     * 
     */
    public P004_TextBase createP004_TextBase() {
        return new P004_TextBase();
    }

    /**
     * Create an instance of {@link DosageInstruction }
     * 
     */
    public DosageInstruction createDosageInstruction() {
        return new DosageInstruction();
    }

    /**
     * Create an instance of {@link P004_SequenceIdBase }
     * 
     */
    public P004_SequenceIdBase createP004_SequenceIdBase() {
        return new P004_SequenceIdBase();
    }

    /**
     * Create an instance of {@link P004_MedicationCodeBase }
     * 
     */
    public P004_MedicationCodeBase createP004_MedicationCodeBase() {
        return new P004_MedicationCodeBase();
    }

    /**
     * Create an instance of {@link P004_PriorityBase }
     * 
     */
    public P004_PriorityBase createP004_PriorityBase() {
        return new P004_PriorityBase();
    }

    /**
     * Create an instance of {@link P004_MkbBase }
     * 
     */
    public P004_MkbBase createP004_MkbBase() {
        return new P004_MkbBase();
    }

    /**
     * Create an instance of {@link P004_NhifCodeBase }
     * 
     */
    public P004_NhifCodeBase createP004_NhifCodeBase() {
        return new P004_NhifCodeBase();
    }

    /**
     * Create an instance of {@link P004_QuantityBase }
     * 
     */
    public P004_QuantityBase createP004_QuantityBase() {
        return new P004_QuantityBase();
    }

    /**
     * Create an instance of {@link P004_QuantityDispensedBase }
     * 
     */
    public P004_QuantityDispensedBase createP004_QuantityDispensedBase() {
        return new P004_QuantityDispensedBase();
    }

    /**
     * Create an instance of {@link P004_IsDispensedBase }
     * 
     */
    public P004_IsDispensedBase createP004_IsDispensedBase() {
        return new P004_IsDispensedBase();
    }

    /**
     * Create an instance of {@link P004_IsSubstitutionAllowedBase }
     * 
     */
    public P004_IsSubstitutionAllowedBase createP004_IsSubstitutionAllowedBase() {
        return new P004_IsSubstitutionAllowedBase();
    }

    /**
     * Create an instance of {@link Medication }
     * 
     */
    public Medication createMedication() {
        return new Medication();
    }

    /**
     * Create an instance of {@link P004_GroupIdentifierBase }
     * 
     */
    public P004_GroupIdentifierBase createP004_GroupIdentifierBase() {
        return new P004_GroupIdentifierBase();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link P004_NrnBase }
     * 
     */
    public P004_NrnBase createP004_NrnBase() {
        return new P004_NrnBase();
    }

    /**
     * Create an instance of {@link P004_LrnBase }
     * 
     */
    public P004_LrnBase createP004_LrnBase() {
        return new P004_LrnBase();
    }

    /**
     * Create an instance of {@link P004_PrescriptionStatusBase }
     * 
     */
    public P004_PrescriptionStatusBase createP004_PrescriptionStatusBase() {
        return new P004_PrescriptionStatusBase();
    }

    /**
     * Create an instance of {@link P004_AuthoredOnBase }
     * 
     */
    public P004_AuthoredOnBase createP004_AuthoredOnBase() {
        return new P004_AuthoredOnBase();
    }

    /**
     * Create an instance of {@link P004_PrescriptionTypeBase }
     * 
     */
    public P004_PrescriptionTypeBase createP004_PrescriptionTypeBase() {
        return new P004_PrescriptionTypeBase();
    }

    /**
     * Create an instance of {@link P004_IsProtocolBasedBase }
     * 
     */
    public P004_IsProtocolBasedBase createP004_IsProtocolBasedBase() {
        return new P004_IsProtocolBasedBase();
    }

    /**
     * Create an instance of {@link P004_ProtocolNumberBase }
     * 
     */
    public P004_ProtocolNumberBase createP004_ProtocolNumberBase() {
        return new P004_ProtocolNumberBase();
    }

    /**
     * Create an instance of {@link P004_ProtocolDateBase }
     * 
     */
    public P004_ProtocolDateBase createP004_ProtocolDateBase() {
        return new P004_ProtocolDateBase();
    }

    /**
     * Create an instance of {@link P004_RhifNumberBase }
     * 
     */
    public P004_RhifNumberBase createP004_RhifNumberBase() {
        return new P004_RhifNumberBase();
    }

    /**
     * Create an instance of {@link P004_OutpatientSheetNumberBase }
     * 
     */
    public P004_OutpatientSheetNumberBase createP004_OutpatientSheetNumberBase() {
        return new P004_OutpatientSheetNumberBase();
    }

    /**
     * Create an instance of {@link P004_DispensationTypeBase }
     * 
     */
    public P004_DispensationTypeBase createP004_DispensationTypeBase() {
        return new P004_DispensationTypeBase();
    }

    /**
     * Create an instance of {@link P004_AllowedRepeatsNumberBase }
     * 
     */
    public P004_AllowedRepeatsNumberBase createP004_AllowedRepeatsNumberBase() {
        return new P004_AllowedRepeatsNumberBase();
    }

    /**
     * Create an instance of {@link P004_IsFulfilledBase }
     * 
     */
    public P004_IsFulfilledBase createP004_IsFulfilledBase() {
        return new P004_IsFulfilledBase();
    }

    /**
     * Create an instance of {@link Prescription }
     * 
     */
    public Prescription createPrescription() {
        return new Prescription();
    }

    /**
     * Create an instance of {@link P004_IdentifierTypeBase }
     * 
     */
    public P004_IdentifierTypeBase createP004_IdentifierTypeBase() {
        return new P004_IdentifierTypeBase();
    }

    /**
     * Create an instance of {@link P004_IdentifierBase }
     * 
     */
    public P004_IdentifierBase createP004_IdentifierBase() {
        return new P004_IdentifierBase();
    }

    /**
     * Create an instance of {@link P004_BirthDateBase }
     * 
     */
    public P004_BirthDateBase createP004_BirthDateBase() {
        return new P004_BirthDateBase();
    }

    /**
     * Create an instance of {@link P004_GenderBase }
     * 
     */
    public P004_GenderBase createP004_GenderBase() {
        return new P004_GenderBase();
    }

    /**
     * Create an instance of {@link P004_AgeBase }
     * 
     */
    public P004_AgeBase createP004_AgeBase() {
        return new P004_AgeBase();
    }

    /**
     * Create an instance of {@link P004_WeightBase }
     * 
     */
    public P004_WeightBase createP004_WeightBase() {
        return new P004_WeightBase();
    }

    /**
     * Create an instance of {@link P004_IsPregnantBase }
     * 
     */
    public P004_IsPregnantBase createP004_IsPregnantBase() {
        return new P004_IsPregnantBase();
    }

    /**
     * Create an instance of {@link P004_IsBreastFeedingBase }
     * 
     */
    public P004_IsBreastFeedingBase createP004_IsBreastFeedingBase() {
        return new P004_IsBreastFeedingBase();
    }

    /**
     * Create an instance of {@link P004_PrBookNumberBase }
     * 
     */
    public P004_PrBookNumberBase createP004_PrBookNumberBase() {
        return new P004_PrBookNumberBase();
    }

    /**
     * Create an instance of {@link P004_HumanNameBase }
     * 
     */
    public P004_HumanNameBase createP004_HumanNameBase() {
        return new P004_HumanNameBase();
    }

    /**
     * Create an instance of {@link P004_AddressBase }
     * 
     */
    public P004_AddressBase createP004_AddressBase() {
        return new P004_AddressBase();
    }

    /**
     * Create an instance of {@link P004_PhoneBase }
     * 
     */
    public P004_PhoneBase createP004_PhoneBase() {
        return new P004_PhoneBase();
    }

    /**
     * Create an instance of {@link P004_EmailBase }
     * 
     */
    public P004_EmailBase createP004_EmailBase() {
        return new P004_EmailBase();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link P004_PmiBase }
     * 
     */
    public P004_PmiBase createP004_PmiBase() {
        return new P004_PmiBase();
    }

    /**
     * Create an instance of {@link P004_QualificationBase }
     * 
     */
    public P004_QualificationBase createP004_QualificationBase() {
        return new P004_QualificationBase();
    }

    /**
     * Create an instance of {@link P004_PracticeNumberBase }
     * 
     */
    public P004_PracticeNumberBase createP004_PracticeNumberBase() {
        return new P004_PracticeNumberBase();
    }

    /**
     * Create an instance of {@link P004_NhifNumberBase }
     * 
     */
    public P004_NhifNumberBase createP004_NhifNumberBase() {
        return new P004_NhifNumberBase();
    }

    /**
     * Create an instance of {@link Requester }
     * 
     */
    public Requester createRequester() {
        return new Requester();
    }

    /**
     * Create an instance of {@link FoundNumber }
     * 
     */
    public FoundNumber createFoundNumber() {
        return new FoundNumber();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link P004_Amount }
     * 
     */
    public P004_Amount createP004_Amount() {
        return new P004_Amount();
    }

    /**
     * Create an instance of {@link P004_AddressDetailsBase }
     * 
     */
    public P004_AddressDetailsBase createP004_AddressDetailsBase() {
        return new P004_AddressDetailsBase();
    }

    /**
     * Create an instance of {@link P004_CityBase }
     * 
     */
    public P004_CityBase createP004_CityBase() {
        return new P004_CityBase();
    }

    /**
     * Create an instance of {@link P004_CountryCodeBase }
     * 
     */
    public P004_CountryCodeBase createP004_CountryCodeBase() {
        return new P004_CountryCodeBase();
    }

    /**
     * Create an instance of {@link P004_DeputyRoleBase }
     * 
     */
    public P004_DeputyRoleBase createP004_DeputyRoleBase() {
        return new P004_DeputyRoleBase();
    }

    /**
     * Create an instance of {@link P004_ExecuteDateBase }
     * 
     */
    public P004_ExecuteDateBase createP004_ExecuteDateBase() {
        return new P004_ExecuteDateBase();
    }

    /**
     * Create an instance of {@link P004_ExpBase }
     * 
     */
    public P004_ExpBase createP004_ExpBase() {
        return new P004_ExpBase();
    }

    /**
     * Create an instance of {@link P004_FamilyNameBase }
     * 
     */
    public P004_FamilyNameBase createP004_FamilyNameBase() {
        return new P004_FamilyNameBase();
    }

    /**
     * Create an instance of {@link P004_FulfilDateBase }
     * 
     */
    public P004_FulfilDateBase createP004_FulfilDateBase() {
        return new P004_FulfilDateBase();
    }

    /**
     * Create an instance of {@link P004_GivenNameBase }
     * 
     */
    public P004_GivenNameBase createP004_GivenNameBase() {
        return new P004_GivenNameBase();
    }

    /**
     * Create an instance of {@link P004_GtinBase }
     * 
     */
    public P004_GtinBase createP004_GtinBase() {
        return new P004_GtinBase();
    }

    /**
     * Create an instance of {@link P004_IsCorrectionBase }
     * 
     */
    public P004_IsCorrectionBase createP004_IsCorrectionBase() {
        return new P004_IsCorrectionBase();
    }

    /**
     * Create an instance of {@link P004_IsInternationalFulfilBase }
     * 
     */
    public P004_IsInternationalFulfilBase createP004_IsInternationalFulfilBase() {
        return new P004_IsInternationalFulfilBase();
    }

    /**
     * Create an instance of {@link P004_IsPatientReceiverBase }
     * 
     */
    public P004_IsPatientReceiverBase createP004_IsPatientReceiverBase() {
        return new P004_IsPatientReceiverBase();
    }

    /**
     * Create an instance of {@link P004_IsProcessingBase }
     * 
     */
    public P004_IsProcessingBase createP004_IsProcessingBase() {
        return new P004_IsProcessingBase();
    }

    /**
     * Create an instance of {@link P004_LotBase }
     * 
     */
    public P004_LotBase createP004_LotBase() {
        return new P004_LotBase();
    }

    /**
     * Create an instance of {@link P004_MdaBase }
     * 
     */
    public P004_MdaBase createP004_MdaBase() {
        return new P004_MdaBase();
    }

    /**
     * Create an instance of {@link P004_MiddleNameBase }
     * 
     */
    public P004_MiddleNameBase createP004_MiddleNameBase() {
        return new P004_MiddleNameBase();
    }

    /**
     * Create an instance of {@link P004_ObservationCodeBase }
     * 
     */
    public P004_ObservationCodeBase createP004_ObservationCodeBase() {
        return new P004_ObservationCodeBase();
    }

    /**
     * Create an instance of {@link P004_PerformedDateTimeBase }
     * 
     */
    public P004_PerformedDateTimeBase createP004_PerformedDateTimeBase() {
        return new P004_PerformedDateTimeBase();
    }

    /**
     * Create an instance of {@link P004_PharmacyNumberBase }
     * 
     */
    public P004_PharmacyNumberBase createP004_PharmacyNumberBase() {
        return new P004_PharmacyNumberBase();
    }

    /**
     * Create an instance of {@link P004_PostCodeBase }
     * 
     */
    public P004_PostCodeBase createP004_PostCodeBase() {
        return new P004_PostCodeBase();
    }

    /**
     * Create an instance of {@link P004_PphiBase }
     * 
     */
    public P004_PphiBase createP004_PphiBase() {
        return new P004_PphiBase();
    }

    /**
     * Create an instance of {@link P004_PpnBase }
     * 
     */
    public P004_PpnBase createP004_PpnBase() {
        return new P004_PpnBase();
    }

    /**
     * Create an instance of {@link P004_ProcedureCategoryBase }
     * 
     */
    public P004_ProcedureCategoryBase createP004_ProcedureCategoryBase() {
        return new P004_ProcedureCategoryBase();
    }

    /**
     * Create an instance of {@link P004_ProcedureMethodBase }
     * 
     */
    public P004_ProcedureMethodBase createP004_ProcedureMethodBase() {
        return new P004_ProcedureMethodBase();
    }

    /**
     * Create an instance of {@link P004_ProcedureStatusBase }
     * 
     */
    public P004_ProcedureStatusBase createP004_ProcedureStatusBase() {
        return new P004_ProcedureStatusBase();
    }

    /**
     * Create an instance of {@link P004_ReasonBase }
     * 
     */
    public P004_ReasonBase createP004_ReasonBase() {
        return new P004_ReasonBase();
    }

    /**
     * Create an instance of {@link P004_ReferenceHighBase }
     * 
     */
    public P004_ReferenceHighBase createP004_ReferenceHighBase() {
        return new P004_ReferenceHighBase();
    }

    /**
     * Create an instance of {@link P004_ReferenceLowBase }
     * 
     */
    public P004_ReferenceLowBase createP004_ReferenceLowBase() {
        return new P004_ReferenceLowBase();
    }

    /**
     * Create an instance of {@link P004_ReferenceTextBase }
     * 
     */
    public P004_ReferenceTextBase createP004_ReferenceTextBase() {
        return new P004_ReferenceTextBase();
    }

    /**
     * Create an instance of {@link P004_ReferralStatusBase }
     * 
     */
    public P004_ReferralStatusBase createP004_ReferralStatusBase() {
        return new P004_ReferralStatusBase();
    }

    /**
     * Create an instance of {@link P004_ReferralSubtypeBase }
     * 
     */
    public P004_ReferralSubtypeBase createP004_ReferralSubtypeBase() {
        return new P004_ReferralSubtypeBase();
    }

    /**
     * Create an instance of {@link P004_ReferralTypeBase }
     * 
     */
    public P004_ReferralTypeBase createP004_ReferralTypeBase() {
        return new P004_ReferralTypeBase();
    }

    /**
     * Create an instance of {@link P004_RhifAreaNumberBase }
     * 
     */
    public P004_RhifAreaNumberBase createP004_RhifAreaNumberBase() {
        return new P004_RhifAreaNumberBase();
    }

    /**
     * Create an instance of {@link P004_RphaNumberBase }
     * 
     */
    public P004_RphaNumberBase createP004_RphaNumberBase() {
        return new P004_RphaNumberBase();
    }

    /**
     * Create an instance of {@link P004_SearchDateBase }
     * 
     */
    public P004_SearchDateBase createP004_SearchDateBase() {
        return new P004_SearchDateBase();
    }

    /**
     * Create an instance of {@link P004_SnBase }
     * 
     */
    public P004_SnBase createP004_SnBase() {
        return new P004_SnBase();
    }

    /**
     * Create an instance of {@link P004_SubstitutionTypeBase }
     * 
     */
    public P004_SubstitutionTypeBase createP004_SubstitutionTypeBase() {
        return new P004_SubstitutionTypeBase();
    }

    /**
     * Create an instance of {@link P004_ValueCodeBase }
     * 
     */
    public P004_ValueCodeBase createP004_ValueCodeBase() {
        return new P004_ValueCodeBase();
    }

    /**
     * Create an instance of {@link P004_ValueDateTimeBase }
     * 
     */
    public P004_ValueDateTimeBase createP004_ValueDateTimeBase() {
        return new P004_ValueDateTimeBase();
    }

    /**
     * Create an instance of {@link P004_ValueNomenclatureBase }
     * 
     */
    public P004_ValueNomenclatureBase createP004_ValueNomenclatureBase() {
        return new P004_ValueNomenclatureBase();
    }

    /**
     * Create an instance of {@link P004_ValueQuantityBase }
     * 
     */
    public P004_ValueQuantityBase createP004_ValueQuantityBase() {
        return new P004_ValueQuantityBase();
    }

    /**
     * Create an instance of {@link P004_ValueScaleBase }
     * 
     */
    public P004_ValueScaleBase createP004_ValueScaleBase() {
        return new P004_ValueScaleBase();
    }

    /**
     * Create an instance of {@link P004_ValueStringBase }
     * 
     */
    public P004_ValueStringBase createP004_ValueStringBase() {
        return new P004_ValueStringBase();
    }

    /**
     * Create an instance of {@link P004_ValueUnitBase }
     * 
     */
    public P004_ValueUnitBase createP004_ValueUnitBase() {
        return new P004_ValueUnitBase();
    }

    /**
     * Create an instance of {@link P004_VerificationCodeBase }
     * 
     */
    public P004_VerificationCodeBase createP004_VerificationCodeBase() {
        return new P004_VerificationCodeBase();
    }

    /**
     * Create an instance of {@link P004_WasSubstitutedBase }
     * 
     */
    public P004_WasSubstitutedBase createP004_WasSubstitutedBase() {
        return new P004_WasSubstitutedBase();
    }

    /**
     * Create an instance of {@link P004_WhenHandedOverBase }
     * 
     */
    public P004_WhenHandedOverBase createP004_WhenHandedOverBase() {
        return new P004_WhenHandedOverBase();
    }

    /**
     * Create an instance of {@link P004_WhenPreparedBase }
     * 
     */
    public P004_WhenPreparedBase createP004_WhenPreparedBase() {
        return new P004_WhenPreparedBase();
    }

    /**
     * Create an instance of {@link OriginalP004_ContentsBase }
     * 
     */
    public OriginalP004_ContentsBase createOriginalP004_ContentsBase() {
        return new OriginalP004_ContentsBase();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_ContentsBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "contents")
    public JAXBElement<P004_ContentsBase> createContents(P004_ContentsBase value) {
        return new JAXBElement<P004_ContentsBase>(_Contents_QNAME, P004_ContentsBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "signature")
    public JAXBElement<Object> createSignature(Object value) {
        return new JAXBElement<Object>(_Signature_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_MessageBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "message")
    public JAXBElement<P004_MessageBase> createMessage(P004_MessageBase value) {
        return new JAXBElement<P004_MessageBase>(_Message_QNAME, P004_MessageBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_SequenceBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "sequence")
    public JAXBElement<P004_SequenceBase> createSequence(P004_SequenceBase value) {
        return new JAXBElement<P004_SequenceBase>(_Sequence_QNAME, P004_SequenceBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_AsNeededBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "asNeeded")
    public JAXBElement<P004_AsNeededBase> createAsNeeded(P004_AsNeededBase value) {
        return new JAXBElement<P004_AsNeededBase>(_AsNeeded_QNAME, P004_AsNeededBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_RouteBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "route")
    public JAXBElement<P004_RouteBase> createRoute(P004_RouteBase value) {
        return new JAXBElement<P004_RouteBase>(_Route_QNAME, P004_RouteBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_DoseQuantityBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "doseQuantity")
    public JAXBElement<P004_DoseQuantityBase> createDoseQuantity(P004_DoseQuantityBase value) {
        return new JAXBElement<P004_DoseQuantityBase>(_DoseQuantity_QNAME, P004_DoseQuantityBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_FrequencyBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "frequency")
    public JAXBElement<P004_FrequencyBase> createFrequency(P004_FrequencyBase value) {
        return new JAXBElement<P004_FrequencyBase>(_Frequency_QNAME, P004_FrequencyBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PeriodBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "period")
    public JAXBElement<P004_PeriodBase> createPeriod(P004_PeriodBase value) {
        return new JAXBElement<P004_PeriodBase>(_Period_QNAME, P004_PeriodBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PeriodUnitBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "periodUnit")
    public JAXBElement<P004_PeriodUnitBase> createPeriodUnit(P004_PeriodUnitBase value) {
        return new JAXBElement<P004_PeriodUnitBase>(_PeriodUnit_QNAME, P004_PeriodUnitBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_BoundsDurationBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "boundsDuration")
    public JAXBElement<P004_BoundsDurationBase> createBoundsDuration(P004_BoundsDurationBase value) {
        return new JAXBElement<P004_BoundsDurationBase>(_BoundsDuration_QNAME, P004_BoundsDurationBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_BoundsDurationUnitBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "boundsDurationUnit")
    public JAXBElement<P004_BoundsDurationUnitBase> createBoundsDurationUnit(P004_BoundsDurationUnitBase value) {
        return new JAXBElement<P004_BoundsDurationUnitBase>(_BoundsDurationUnit_QNAME, P004_BoundsDurationUnitBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_TextBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "text")
    public JAXBElement<P004_TextBase> createText(P004_TextBase value) {
        return new JAXBElement<P004_TextBase>(_Text_QNAME, P004_TextBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_SequenceIdBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "sequenceId")
    public JAXBElement<P004_SequenceIdBase> createSequenceId(P004_SequenceIdBase value) {
        return new JAXBElement<P004_SequenceIdBase>(_SequenceId_QNAME, P004_SequenceIdBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_MedicationCodeBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "medicationCode")
    public JAXBElement<P004_MedicationCodeBase> createMedicationCode(P004_MedicationCodeBase value) {
        return new JAXBElement<P004_MedicationCodeBase>(_MedicationCode_QNAME, P004_MedicationCodeBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PriorityBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "priority")
    public JAXBElement<P004_PriorityBase> createPriority(P004_PriorityBase value) {
        return new JAXBElement<P004_PriorityBase>(_Priority_QNAME, P004_PriorityBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_MkbBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "mkb")
    public JAXBElement<P004_MkbBase> createMkb(P004_MkbBase value) {
        return new JAXBElement<P004_MkbBase>(_Mkb_QNAME, P004_MkbBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_NhifCodeBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "nhifCode")
    public JAXBElement<P004_NhifCodeBase> createNhifCode(P004_NhifCodeBase value) {
        return new JAXBElement<P004_NhifCodeBase>(_NhifCode_QNAME, P004_NhifCodeBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_QuantityBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "quantity")
    public JAXBElement<P004_QuantityBase> createQuantity(P004_QuantityBase value) {
        return new JAXBElement<P004_QuantityBase>(_Quantity_QNAME, P004_QuantityBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_QuantityDispensedBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "quantityDispensed")
    public JAXBElement<P004_QuantityDispensedBase> createQuantityDispensed(P004_QuantityDispensedBase value) {
        return new JAXBElement<P004_QuantityDispensedBase>(_QuantityDispensed_QNAME, P004_QuantityDispensedBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IsDispensedBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "isDispensed")
    public JAXBElement<P004_IsDispensedBase> createIsDispensed(P004_IsDispensedBase value) {
        return new JAXBElement<P004_IsDispensedBase>(_IsDispensed_QNAME, P004_IsDispensedBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IsSubstitutionAllowedBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "isSubstitutionAllowed")
    public JAXBElement<P004_IsSubstitutionAllowedBase> createIsSubstitutionAllowed(P004_IsSubstitutionAllowedBase value) {
        return new JAXBElement<P004_IsSubstitutionAllowedBase>(_IsSubstitutionAllowed_QNAME, P004_IsSubstitutionAllowedBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_GroupIdentifierBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "groupIdentifier")
    public JAXBElement<P004_GroupIdentifierBase> createGroupIdentifier(P004_GroupIdentifierBase value) {
        return new JAXBElement<P004_GroupIdentifierBase>(_GroupIdentifier_QNAME, P004_GroupIdentifierBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_NrnBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "nrnPrescription")
    public JAXBElement<P004_NrnBase> createNrnPrescription(P004_NrnBase value) {
        return new JAXBElement<P004_NrnBase>(_NrnPrescription_QNAME, P004_NrnBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_LrnBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "lrn")
    public JAXBElement<P004_LrnBase> createLrn(P004_LrnBase value) {
        return new JAXBElement<P004_LrnBase>(_Lrn_QNAME, P004_LrnBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PrescriptionStatusBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "status")
    public JAXBElement<P004_PrescriptionStatusBase> createStatus(P004_PrescriptionStatusBase value) {
        return new JAXBElement<P004_PrescriptionStatusBase>(_Status_QNAME, P004_PrescriptionStatusBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_AuthoredOnBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "authoredOn")
    public JAXBElement<P004_AuthoredOnBase> createAuthoredOn(P004_AuthoredOnBase value) {
        return new JAXBElement<P004_AuthoredOnBase>(_AuthoredOn_QNAME, P004_AuthoredOnBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PrescriptionTypeBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "category")
    public JAXBElement<P004_PrescriptionTypeBase> createCategory(P004_PrescriptionTypeBase value) {
        return new JAXBElement<P004_PrescriptionTypeBase>(_Category_QNAME, P004_PrescriptionTypeBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IsProtocolBasedBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "isProtocolBased")
    public JAXBElement<P004_IsProtocolBasedBase> createIsProtocolBased(P004_IsProtocolBasedBase value) {
        return new JAXBElement<P004_IsProtocolBasedBase>(_IsProtocolBased_QNAME, P004_IsProtocolBasedBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_ProtocolNumberBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "protocolNumber")
    public JAXBElement<P004_ProtocolNumberBase> createProtocolNumber(P004_ProtocolNumberBase value) {
        return new JAXBElement<P004_ProtocolNumberBase>(_ProtocolNumber_QNAME, P004_ProtocolNumberBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_ProtocolDateBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "protocolDate")
    public JAXBElement<P004_ProtocolDateBase> createProtocolDate(P004_ProtocolDateBase value) {
        return new JAXBElement<P004_ProtocolDateBase>(_ProtocolDate_QNAME, P004_ProtocolDateBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_RhifNumberBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "rhifNumber")
    public JAXBElement<P004_RhifNumberBase> createRhifNumber(P004_RhifNumberBase value) {
        return new JAXBElement<P004_RhifNumberBase>(_RhifNumber_QNAME, P004_RhifNumberBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_OutpatientSheetNumberBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "basedOn")
    public JAXBElement<P004_OutpatientSheetNumberBase> createBasedOn(P004_OutpatientSheetNumberBase value) {
        return new JAXBElement<P004_OutpatientSheetNumberBase>(_BasedOn_QNAME, P004_OutpatientSheetNumberBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_DispensationTypeBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "dispensationType")
    public JAXBElement<P004_DispensationTypeBase> createDispensationType(P004_DispensationTypeBase value) {
        return new JAXBElement<P004_DispensationTypeBase>(_DispensationType_QNAME, P004_DispensationTypeBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_AllowedRepeatsNumberBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "allowedRepeatsNumber")
    public JAXBElement<P004_AllowedRepeatsNumberBase> createAllowedRepeatsNumber(P004_AllowedRepeatsNumberBase value) {
        return new JAXBElement<P004_AllowedRepeatsNumberBase>(_AllowedRepeatsNumber_QNAME, P004_AllowedRepeatsNumberBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IsFulfilledBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "isFulfilled")
    public JAXBElement<P004_IsFulfilledBase> createIsFulfilled(P004_IsFulfilledBase value) {
        return new JAXBElement<P004_IsFulfilledBase>(_IsFulfilled_QNAME, P004_IsFulfilledBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IdentifierTypeBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "identifierType")
    public JAXBElement<P004_IdentifierTypeBase> createIdentifierType(P004_IdentifierTypeBase value) {
        return new JAXBElement<P004_IdentifierTypeBase>(_IdentifierType_QNAME, P004_IdentifierTypeBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IdentifierBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "identifier")
    public JAXBElement<P004_IdentifierBase> createIdentifier(P004_IdentifierBase value) {
        return new JAXBElement<P004_IdentifierBase>(_Identifier_QNAME, P004_IdentifierBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_BirthDateBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "birthDate")
    public JAXBElement<P004_BirthDateBase> createBirthDate(P004_BirthDateBase value) {
        return new JAXBElement<P004_BirthDateBase>(_BirthDate_QNAME, P004_BirthDateBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_GenderBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "gender")
    public JAXBElement<P004_GenderBase> createGender(P004_GenderBase value) {
        return new JAXBElement<P004_GenderBase>(_Gender_QNAME, P004_GenderBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_AgeBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "age")
    public JAXBElement<P004_AgeBase> createAge(P004_AgeBase value) {
        return new JAXBElement<P004_AgeBase>(_Age_QNAME, P004_AgeBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_WeightBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "weight")
    public JAXBElement<P004_WeightBase> createWeight(P004_WeightBase value) {
        return new JAXBElement<P004_WeightBase>(_Weight_QNAME, P004_WeightBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IsPregnantBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "isPregnant")
    public JAXBElement<P004_IsPregnantBase> createIsPregnant(P004_IsPregnantBase value) {
        return new JAXBElement<P004_IsPregnantBase>(_IsPregnant_QNAME, P004_IsPregnantBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_IsBreastFeedingBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "isBreastFeeding")
    public JAXBElement<P004_IsBreastFeedingBase> createIsBreastFeeding(P004_IsBreastFeedingBase value) {
        return new JAXBElement<P004_IsBreastFeedingBase>(_IsBreastFeeding_QNAME, P004_IsBreastFeedingBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PrBookNumberBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "prBookNumber")
    public JAXBElement<P004_PrBookNumberBase> createPrBookNumber(P004_PrBookNumberBase value) {
        return new JAXBElement<P004_PrBookNumberBase>(_PrBookNumber_QNAME, P004_PrBookNumberBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_HumanNameBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "name")
    public JAXBElement<P004_HumanNameBase> createName(P004_HumanNameBase value) {
        return new JAXBElement<P004_HumanNameBase>(_Name_QNAME, P004_HumanNameBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_AddressBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "address")
    public JAXBElement<P004_AddressBase> createAddress(P004_AddressBase value) {
        return new JAXBElement<P004_AddressBase>(_Address_QNAME, P004_AddressBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PhoneBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "phone")
    public JAXBElement<P004_PhoneBase> createPhone(P004_PhoneBase value) {
        return new JAXBElement<P004_PhoneBase>(_Phone_QNAME, P004_PhoneBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_EmailBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "email")
    public JAXBElement<P004_EmailBase> createEmail(P004_EmailBase value) {
        return new JAXBElement<P004_EmailBase>(_Email_QNAME, P004_EmailBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PmiBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "pmi")
    public JAXBElement<P004_PmiBase> createPmi(P004_PmiBase value) {
        return new JAXBElement<P004_PmiBase>(_Pmi_QNAME, P004_PmiBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_QualificationBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "qualification")
    public JAXBElement<P004_QualificationBase> createQualification(P004_QualificationBase value) {
        return new JAXBElement<P004_QualificationBase>(_Qualification_QNAME, P004_QualificationBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_PracticeNumberBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "practiceNumber")
    public JAXBElement<P004_PracticeNumberBase> createPracticeNumber(P004_PracticeNumberBase value) {
        return new JAXBElement<P004_PracticeNumberBase>(_PracticeNumber_QNAME, P004_PracticeNumberBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P004_NhifNumberBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "nhifNumber")
    public JAXBElement<P004_NhifNumberBase> createNhifNumber(P004_NhifNumberBase value) {
        return new JAXBElement<P004_NhifNumberBase>(_NhifNumber_QNAME, P004_NhifNumberBase.class, null, value);
    }

}
