//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p004;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contentsBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contentsBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.his.bg}contentsBase"&gt;
 *       &lt;redefine&gt;
 *         &lt;complexType name="contentsBase"&gt;
 *           &lt;complexContent&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *               &lt;sequence&gt;
 *               &lt;/sequence&gt;
 *             &lt;/restriction&gt;
 *           &lt;/complexContent&gt;
 *         &lt;/complexType&gt;
 *       &lt;/redefine&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://www.his.bg}foundNumber"/&gt;
 *         &lt;element ref="{https://www.his.bg}results" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contentsBase", propOrder = {
    "foundNumber",
    "results"
})
public class P004_ContentsBase
    extends OriginalP004_ContentsBase
{

    @XmlElement(required = true)
    protected FoundNumber foundNumber;
    protected List<Results> results;

    /**
     * Gets the value of the foundNumber property.
     * 
     * @return
     *     possible object is
     *     {@link FoundNumber }
     *     
     */
    public FoundNumber getFoundNumber() {
        return foundNumber;
    }

    /**
     * Sets the value of the foundNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoundNumber }
     *     
     */
    public void setFoundNumber(FoundNumber value) {
        this.foundNumber = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the results property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Results }
     * 
     * 
     */
    public List<Results> getResults() {
        if (results == null) {
            results = new ArrayList<Results>();
        }
        return this.results;
    }

}
