//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p004;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://www.his.bg}identifierType"/&gt;
 *         &lt;element ref="{https://www.his.bg}identifier"/&gt;
 *         &lt;element ref="{https://www.his.bg}birthDate"/&gt;
 *         &lt;element ref="{https://www.his.bg}gender"/&gt;
 *         &lt;element ref="{https://www.his.bg}age"/&gt;
 *         &lt;element ref="{https://www.his.bg}weight" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}isPregnant"/&gt;
 *         &lt;element ref="{https://www.his.bg}isBreastFeeding"/&gt;
 *         &lt;element ref="{https://www.his.bg}prBookNumber" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}name"/&gt;
 *         &lt;element ref="{https://www.his.bg}address"/&gt;
 *         &lt;element ref="{https://www.his.bg}phone" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}email" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifierType",
    "identifier",
    "birthDate",
    "gender",
    "age",
    "weight",
    "isPregnant",
    "isBreastFeeding",
    "prBookNumber",
    "name",
    "address",
    "phone",
    "email"
})
@XmlRootElement(name = "subject")
public class Subject {

    @XmlElement(required = true)
    protected P004_IdentifierTypeBase identifierType;
    @XmlElement(required = true)
    protected P004_IdentifierBase identifier;
    @XmlElement(required = true)
    protected P004_BirthDateBase birthDate;
    @XmlElement(required = true)
    protected P004_GenderBase gender;
    @XmlElement(required = true)
    protected P004_AgeBase age;
    protected P004_WeightBase weight;
    @XmlElement(required = true)
    protected P004_IsPregnantBase isPregnant;
    @XmlElement(required = true)
    protected P004_IsBreastFeedingBase isBreastFeeding;
    protected P004_PrBookNumberBase prBookNumber;
    @XmlElement(required = true)
    protected P004_HumanNameBase name;
    @XmlElement(required = true)
    protected P004_AddressBase address;
    protected P004_PhoneBase phone;
    protected P004_EmailBase email;

    /**
     * Gets the value of the identifierType property.
     * 
     * @return
     *     possible object is
     *     {@link P004_IdentifierTypeBase }
     *     
     */
    public P004_IdentifierTypeBase getIdentifierType() {
        return identifierType;
    }

    /**
     * Sets the value of the identifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_IdentifierTypeBase }
     *     
     */
    public void setIdentifierType(P004_IdentifierTypeBase value) {
        this.identifierType = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link P004_IdentifierBase }
     *     
     */
    public P004_IdentifierBase getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_IdentifierBase }
     *     
     */
    public void setIdentifier(P004_IdentifierBase value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link P004_BirthDateBase }
     *     
     */
    public P004_BirthDateBase getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_BirthDateBase }
     *     
     */
    public void setBirthDate(P004_BirthDateBase value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link P004_GenderBase }
     *     
     */
    public P004_GenderBase getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_GenderBase }
     *     
     */
    public void setGender(P004_GenderBase value) {
        this.gender = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link P004_AgeBase }
     *     
     */
    public P004_AgeBase getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_AgeBase }
     *     
     */
    public void setAge(P004_AgeBase value) {
        this.age = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link P004_WeightBase }
     *     
     */
    public P004_WeightBase getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_WeightBase }
     *     
     */
    public void setWeight(P004_WeightBase value) {
        this.weight = value;
    }

    /**
     * Gets the value of the isPregnant property.
     * 
     * @return
     *     possible object is
     *     {@link P004_IsPregnantBase }
     *     
     */
    public P004_IsPregnantBase getIsPregnant() {
        return isPregnant;
    }

    /**
     * Sets the value of the isPregnant property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_IsPregnantBase }
     *     
     */
    public void setIsPregnant(P004_IsPregnantBase value) {
        this.isPregnant = value;
    }

    /**
     * Gets the value of the isBreastFeeding property.
     * 
     * @return
     *     possible object is
     *     {@link P004_IsBreastFeedingBase }
     *     
     */
    public P004_IsBreastFeedingBase getIsBreastFeeding() {
        return isBreastFeeding;
    }

    /**
     * Sets the value of the isBreastFeeding property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_IsBreastFeedingBase }
     *     
     */
    public void setIsBreastFeeding(P004_IsBreastFeedingBase value) {
        this.isBreastFeeding = value;
    }

    /**
     * Gets the value of the prBookNumber property.
     * 
     * @return
     *     possible object is
     *     {@link P004_PrBookNumberBase }
     *     
     */
    public P004_PrBookNumberBase getPrBookNumber() {
        return prBookNumber;
    }

    /**
     * Sets the value of the prBookNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_PrBookNumberBase }
     *     
     */
    public void setPrBookNumber(P004_PrBookNumberBase value) {
        this.prBookNumber = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link P004_HumanNameBase }
     *     
     */
    public P004_HumanNameBase getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_HumanNameBase }
     *     
     */
    public void setName(P004_HumanNameBase value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link P004_AddressBase }
     *     
     */
    public P004_AddressBase getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_AddressBase }
     *     
     */
    public void setAddress(P004_AddressBase value) {
        this.address = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link P004_PhoneBase }
     *     
     */
    public P004_PhoneBase getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_PhoneBase }
     *     
     */
    public void setPhone(P004_PhoneBase value) {
        this.phone = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link P004_EmailBase }
     *     
     */
    public P004_EmailBase getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link P004_EmailBase }
     *     
     */
    public void setEmail(P004_EmailBase value) {
        this.email = value;
    }

}
