//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p003;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.eprescription.model.p003 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Contents_QNAME = new QName("https://www.his.bg", "contents");
    private final static QName _Signature_QNAME = new QName("https://www.his.bg", "signature");
    private final static QName _Message_QNAME = new QName("https://www.his.bg", "message");
    private final static QName _NrnPrescription_QNAME = new QName("https://www.his.bg", "nrnPrescription");
    private final static QName _Lrn_QNAME = new QName("https://www.his.bg", "lrn");
    private final static QName _Pmi_QNAME = new QName("https://www.his.bg", "pmi");
    private final static QName _IdentifierType_QNAME = new QName("https://www.his.bg", "identifierType");
    private final static QName _Identifier_QNAME = new QName("https://www.his.bg", "identifier");
    private final static QName _BirthDate_QNAME = new QName("https://www.his.bg", "birthDate");
    private final static QName _Name_QNAME = new QName("https://www.his.bg", "name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.eprescription.model.p003
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sender }
     * 
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link SenderId }
     * 
     */
    public SenderId createSenderId() {
        return new SenderId();
    }

    /**
     * Create an instance of {@link Recipient }
     * 
     */
    public Recipient createRecipient() {
        return new Recipient();
    }

    /**
     * Create an instance of {@link RecipientId }
     * 
     */
    public RecipientId createRecipientId() {
        return new RecipientId();
    }

    /**
     * Create an instance of {@link MessageId }
     * 
     */
    public MessageId createMessageId() {
        return new MessageId();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link CreatedOn }
     * 
     */
    public CreatedOn createCreatedOn() {
        return new CreatedOn();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link P003_ContentsBase }
     * 
     */
    public P003_ContentsBase createP003_ContentsBase() {
        return new P003_ContentsBase();
    }

    /**
     * Create an instance of {@link P003_MessageBase }
     * 
     */
    public P003_MessageBase createP003_MessageBase() {
        return new P003_MessageBase();
    }

    /**
     * Create an instance of {@link P003_NrnBase }
     * 
     */
    public P003_NrnBase createP003_NrnBase() {
        return new P003_NrnBase();
    }

    /**
     * Create an instance of {@link P003_LrnBase }
     * 
     */
    public P003_LrnBase createP003_LrnBase() {
        return new P003_LrnBase();
    }

    /**
     * Create an instance of {@link P003_PmiBase }
     * 
     */
    public P003_PmiBase createP003_PmiBase() {
        return new P003_PmiBase();
    }

    /**
     * Create an instance of {@link P003_IdentifierTypeBase }
     * 
     */
    public P003_IdentifierTypeBase createP003_IdentifierTypeBase() {
        return new P003_IdentifierTypeBase();
    }

    /**
     * Create an instance of {@link P003_IdentifierBase }
     * 
     */
    public P003_IdentifierBase createP003_IdentifierBase() {
        return new P003_IdentifierBase();
    }

    /**
     * Create an instance of {@link P003_BirthDateBase }
     * 
     */
    public P003_BirthDateBase createP003_BirthDateBase() {
        return new P003_BirthDateBase();
    }

    /**
     * Create an instance of {@link P003_HumanNameBase }
     * 
     */
    public P003_HumanNameBase createP003_HumanNameBase() {
        return new P003_HumanNameBase();
    }

    /**
     * Create an instance of {@link P003_Amount }
     * 
     */
    public P003_Amount createP003_Amount() {
        return new P003_Amount();
    }

    /**
     * Create an instance of {@link P003_AddressDetailsBase }
     * 
     */
    public P003_AddressDetailsBase createP003_AddressDetailsBase() {
        return new P003_AddressDetailsBase();
    }

    /**
     * Create an instance of {@link P003_AgeBase }
     * 
     */
    public P003_AgeBase createP003_AgeBase() {
        return new P003_AgeBase();
    }

    /**
     * Create an instance of {@link P003_AllowedRepeatsNumberBase }
     * 
     */
    public P003_AllowedRepeatsNumberBase createP003_AllowedRepeatsNumberBase() {
        return new P003_AllowedRepeatsNumberBase();
    }

    /**
     * Create an instance of {@link P003_AsNeededBase }
     * 
     */
    public P003_AsNeededBase createP003_AsNeededBase() {
        return new P003_AsNeededBase();
    }

    /**
     * Create an instance of {@link P003_BoundsDurationBase }
     * 
     */
    public P003_BoundsDurationBase createP003_BoundsDurationBase() {
        return new P003_BoundsDurationBase();
    }

    /**
     * Create an instance of {@link P003_BoundsDurationUnitBase }
     * 
     */
    public P003_BoundsDurationUnitBase createP003_BoundsDurationUnitBase() {
        return new P003_BoundsDurationUnitBase();
    }

    /**
     * Create an instance of {@link P003_CityBase }
     * 
     */
    public P003_CityBase createP003_CityBase() {
        return new P003_CityBase();
    }

    /**
     * Create an instance of {@link P003_CountryCodeBase }
     * 
     */
    public P003_CountryCodeBase createP003_CountryCodeBase() {
        return new P003_CountryCodeBase();
    }

    /**
     * Create an instance of {@link P003_DeputyRoleBase }
     * 
     */
    public P003_DeputyRoleBase createP003_DeputyRoleBase() {
        return new P003_DeputyRoleBase();
    }

    /**
     * Create an instance of {@link P003_DispensationTypeBase }
     * 
     */
    public P003_DispensationTypeBase createP003_DispensationTypeBase() {
        return new P003_DispensationTypeBase();
    }

    /**
     * Create an instance of {@link P003_DoseQuantityBase }
     * 
     */
    public P003_DoseQuantityBase createP003_DoseQuantityBase() {
        return new P003_DoseQuantityBase();
    }

    /**
     * Create an instance of {@link P003_EmailBase }
     * 
     */
    public P003_EmailBase createP003_EmailBase() {
        return new P003_EmailBase();
    }

    /**
     * Create an instance of {@link P003_ExecuteDateBase }
     * 
     */
    public P003_ExecuteDateBase createP003_ExecuteDateBase() {
        return new P003_ExecuteDateBase();
    }

    /**
     * Create an instance of {@link P003_ExpBase }
     * 
     */
    public P003_ExpBase createP003_ExpBase() {
        return new P003_ExpBase();
    }

    /**
     * Create an instance of {@link P003_FamilyNameBase }
     * 
     */
    public P003_FamilyNameBase createP003_FamilyNameBase() {
        return new P003_FamilyNameBase();
    }

    /**
     * Create an instance of {@link P003_FrequencyBase }
     * 
     */
    public P003_FrequencyBase createP003_FrequencyBase() {
        return new P003_FrequencyBase();
    }

    /**
     * Create an instance of {@link P003_FulfilDateBase }
     * 
     */
    public P003_FulfilDateBase createP003_FulfilDateBase() {
        return new P003_FulfilDateBase();
    }

    /**
     * Create an instance of {@link P003_GenderBase }
     * 
     */
    public P003_GenderBase createP003_GenderBase() {
        return new P003_GenderBase();
    }

    /**
     * Create an instance of {@link P003_GivenNameBase }
     * 
     */
    public P003_GivenNameBase createP003_GivenNameBase() {
        return new P003_GivenNameBase();
    }

    /**
     * Create an instance of {@link P003_GroupIdentifierBase }
     * 
     */
    public P003_GroupIdentifierBase createP003_GroupIdentifierBase() {
        return new P003_GroupIdentifierBase();
    }

    /**
     * Create an instance of {@link P003_GtinBase }
     * 
     */
    public P003_GtinBase createP003_GtinBase() {
        return new P003_GtinBase();
    }

    /**
     * Create an instance of {@link P003_IsBreastFeedingBase }
     * 
     */
    public P003_IsBreastFeedingBase createP003_IsBreastFeedingBase() {
        return new P003_IsBreastFeedingBase();
    }

    /**
     * Create an instance of {@link P003_IsCorrectionBase }
     * 
     */
    public P003_IsCorrectionBase createP003_IsCorrectionBase() {
        return new P003_IsCorrectionBase();
    }

    /**
     * Create an instance of {@link P003_IsDispensedBase }
     * 
     */
    public P003_IsDispensedBase createP003_IsDispensedBase() {
        return new P003_IsDispensedBase();
    }

    /**
     * Create an instance of {@link P003_IsFulfilledBase }
     * 
     */
    public P003_IsFulfilledBase createP003_IsFulfilledBase() {
        return new P003_IsFulfilledBase();
    }

    /**
     * Create an instance of {@link P003_IsInternationalFulfilBase }
     * 
     */
    public P003_IsInternationalFulfilBase createP003_IsInternationalFulfilBase() {
        return new P003_IsInternationalFulfilBase();
    }

    /**
     * Create an instance of {@link P003_IsPatientReceiverBase }
     * 
     */
    public P003_IsPatientReceiverBase createP003_IsPatientReceiverBase() {
        return new P003_IsPatientReceiverBase();
    }

    /**
     * Create an instance of {@link P003_IsPregnantBase }
     * 
     */
    public P003_IsPregnantBase createP003_IsPregnantBase() {
        return new P003_IsPregnantBase();
    }

    /**
     * Create an instance of {@link P003_IsProcessingBase }
     * 
     */
    public P003_IsProcessingBase createP003_IsProcessingBase() {
        return new P003_IsProcessingBase();
    }

    /**
     * Create an instance of {@link P003_IsProtocolBasedBase }
     * 
     */
    public P003_IsProtocolBasedBase createP003_IsProtocolBasedBase() {
        return new P003_IsProtocolBasedBase();
    }

    /**
     * Create an instance of {@link P003_IsSubstitutionAllowedBase }
     * 
     */
    public P003_IsSubstitutionAllowedBase createP003_IsSubstitutionAllowedBase() {
        return new P003_IsSubstitutionAllowedBase();
    }

    /**
     * Create an instance of {@link P003_AuthoredOnBase }
     * 
     */
    public P003_AuthoredOnBase createP003_AuthoredOnBase() {
        return new P003_AuthoredOnBase();
    }

    /**
     * Create an instance of {@link P003_LotBase }
     * 
     */
    public P003_LotBase createP003_LotBase() {
        return new P003_LotBase();
    }

    /**
     * Create an instance of {@link P003_MdaBase }
     * 
     */
    public P003_MdaBase createP003_MdaBase() {
        return new P003_MdaBase();
    }

    /**
     * Create an instance of {@link P003_MedicationCodeBase }
     * 
     */
    public P003_MedicationCodeBase createP003_MedicationCodeBase() {
        return new P003_MedicationCodeBase();
    }

    /**
     * Create an instance of {@link P003_MiddleNameBase }
     * 
     */
    public P003_MiddleNameBase createP003_MiddleNameBase() {
        return new P003_MiddleNameBase();
    }

    /**
     * Create an instance of {@link P003_MkbBase }
     * 
     */
    public P003_MkbBase createP003_MkbBase() {
        return new P003_MkbBase();
    }

    /**
     * Create an instance of {@link P003_NhifCodeBase }
     * 
     */
    public P003_NhifCodeBase createP003_NhifCodeBase() {
        return new P003_NhifCodeBase();
    }

    /**
     * Create an instance of {@link P003_NhifNumberBase }
     * 
     */
    public P003_NhifNumberBase createP003_NhifNumberBase() {
        return new P003_NhifNumberBase();
    }

    /**
     * Create an instance of {@link P003_ObservationCodeBase }
     * 
     */
    public P003_ObservationCodeBase createP003_ObservationCodeBase() {
        return new P003_ObservationCodeBase();
    }

    /**
     * Create an instance of {@link P003_OutpatientSheetNumberBase }
     * 
     */
    public P003_OutpatientSheetNumberBase createP003_OutpatientSheetNumberBase() {
        return new P003_OutpatientSheetNumberBase();
    }

    /**
     * Create an instance of {@link P003_PerformedDateTimeBase }
     * 
     */
    public P003_PerformedDateTimeBase createP003_PerformedDateTimeBase() {
        return new P003_PerformedDateTimeBase();
    }

    /**
     * Create an instance of {@link P003_PeriodBase }
     * 
     */
    public P003_PeriodBase createP003_PeriodBase() {
        return new P003_PeriodBase();
    }

    /**
     * Create an instance of {@link P003_PeriodUnitBase }
     * 
     */
    public P003_PeriodUnitBase createP003_PeriodUnitBase() {
        return new P003_PeriodUnitBase();
    }

    /**
     * Create an instance of {@link P003_PharmacyNumberBase }
     * 
     */
    public P003_PharmacyNumberBase createP003_PharmacyNumberBase() {
        return new P003_PharmacyNumberBase();
    }

    /**
     * Create an instance of {@link P003_PhoneBase }
     * 
     */
    public P003_PhoneBase createP003_PhoneBase() {
        return new P003_PhoneBase();
    }

    /**
     * Create an instance of {@link P003_PostCodeBase }
     * 
     */
    public P003_PostCodeBase createP003_PostCodeBase() {
        return new P003_PostCodeBase();
    }

    /**
     * Create an instance of {@link P003_PphiBase }
     * 
     */
    public P003_PphiBase createP003_PphiBase() {
        return new P003_PphiBase();
    }

    /**
     * Create an instance of {@link P003_PpnBase }
     * 
     */
    public P003_PpnBase createP003_PpnBase() {
        return new P003_PpnBase();
    }

    /**
     * Create an instance of {@link P003_PracticeNumberBase }
     * 
     */
    public P003_PracticeNumberBase createP003_PracticeNumberBase() {
        return new P003_PracticeNumberBase();
    }

    /**
     * Create an instance of {@link P003_PrBookNumberBase }
     * 
     */
    public P003_PrBookNumberBase createP003_PrBookNumberBase() {
        return new P003_PrBookNumberBase();
    }

    /**
     * Create an instance of {@link P003_PrescriptionStatusBase }
     * 
     */
    public P003_PrescriptionStatusBase createP003_PrescriptionStatusBase() {
        return new P003_PrescriptionStatusBase();
    }

    /**
     * Create an instance of {@link P003_PrescriptionTypeBase }
     * 
     */
    public P003_PrescriptionTypeBase createP003_PrescriptionTypeBase() {
        return new P003_PrescriptionTypeBase();
    }

    /**
     * Create an instance of {@link P003_PriorityBase }
     * 
     */
    public P003_PriorityBase createP003_PriorityBase() {
        return new P003_PriorityBase();
    }

    /**
     * Create an instance of {@link P003_ProcedureCategoryBase }
     * 
     */
    public P003_ProcedureCategoryBase createP003_ProcedureCategoryBase() {
        return new P003_ProcedureCategoryBase();
    }

    /**
     * Create an instance of {@link P003_ProcedureMethodBase }
     * 
     */
    public P003_ProcedureMethodBase createP003_ProcedureMethodBase() {
        return new P003_ProcedureMethodBase();
    }

    /**
     * Create an instance of {@link P003_ProcedureStatusBase }
     * 
     */
    public P003_ProcedureStatusBase createP003_ProcedureStatusBase() {
        return new P003_ProcedureStatusBase();
    }

    /**
     * Create an instance of {@link P003_ProtocolDateBase }
     * 
     */
    public P003_ProtocolDateBase createP003_ProtocolDateBase() {
        return new P003_ProtocolDateBase();
    }

    /**
     * Create an instance of {@link P003_ProtocolNumberBase }
     * 
     */
    public P003_ProtocolNumberBase createP003_ProtocolNumberBase() {
        return new P003_ProtocolNumberBase();
    }

    /**
     * Create an instance of {@link P003_QualificationBase }
     * 
     */
    public P003_QualificationBase createP003_QualificationBase() {
        return new P003_QualificationBase();
    }

    /**
     * Create an instance of {@link P003_QuantityBase }
     * 
     */
    public P003_QuantityBase createP003_QuantityBase() {
        return new P003_QuantityBase();
    }

    /**
     * Create an instance of {@link P003_QuantityDispensedBase }
     * 
     */
    public P003_QuantityDispensedBase createP003_QuantityDispensedBase() {
        return new P003_QuantityDispensedBase();
    }

    /**
     * Create an instance of {@link P003_ReasonBase }
     * 
     */
    public P003_ReasonBase createP003_ReasonBase() {
        return new P003_ReasonBase();
    }

    /**
     * Create an instance of {@link P003_ReferenceHighBase }
     * 
     */
    public P003_ReferenceHighBase createP003_ReferenceHighBase() {
        return new P003_ReferenceHighBase();
    }

    /**
     * Create an instance of {@link P003_ReferenceLowBase }
     * 
     */
    public P003_ReferenceLowBase createP003_ReferenceLowBase() {
        return new P003_ReferenceLowBase();
    }

    /**
     * Create an instance of {@link P003_ReferenceTextBase }
     * 
     */
    public P003_ReferenceTextBase createP003_ReferenceTextBase() {
        return new P003_ReferenceTextBase();
    }

    /**
     * Create an instance of {@link P003_ReferralStatusBase }
     * 
     */
    public P003_ReferralStatusBase createP003_ReferralStatusBase() {
        return new P003_ReferralStatusBase();
    }

    /**
     * Create an instance of {@link P003_ReferralSubtypeBase }
     * 
     */
    public P003_ReferralSubtypeBase createP003_ReferralSubtypeBase() {
        return new P003_ReferralSubtypeBase();
    }

    /**
     * Create an instance of {@link P003_ReferralTypeBase }
     * 
     */
    public P003_ReferralTypeBase createP003_ReferralTypeBase() {
        return new P003_ReferralTypeBase();
    }

    /**
     * Create an instance of {@link P003_RhifAreaNumberBase }
     * 
     */
    public P003_RhifAreaNumberBase createP003_RhifAreaNumberBase() {
        return new P003_RhifAreaNumberBase();
    }

    /**
     * Create an instance of {@link P003_RhifNumberBase }
     * 
     */
    public P003_RhifNumberBase createP003_RhifNumberBase() {
        return new P003_RhifNumberBase();
    }

    /**
     * Create an instance of {@link P003_RouteBase }
     * 
     */
    public P003_RouteBase createP003_RouteBase() {
        return new P003_RouteBase();
    }

    /**
     * Create an instance of {@link P003_RphaNumberBase }
     * 
     */
    public P003_RphaNumberBase createP003_RphaNumberBase() {
        return new P003_RphaNumberBase();
    }

    /**
     * Create an instance of {@link P003_SearchDateBase }
     * 
     */
    public P003_SearchDateBase createP003_SearchDateBase() {
        return new P003_SearchDateBase();
    }

    /**
     * Create an instance of {@link P003_SequenceBase }
     * 
     */
    public P003_SequenceBase createP003_SequenceBase() {
        return new P003_SequenceBase();
    }

    /**
     * Create an instance of {@link P003_SequenceIdBase }
     * 
     */
    public P003_SequenceIdBase createP003_SequenceIdBase() {
        return new P003_SequenceIdBase();
    }

    /**
     * Create an instance of {@link P003_SnBase }
     * 
     */
    public P003_SnBase createP003_SnBase() {
        return new P003_SnBase();
    }

    /**
     * Create an instance of {@link P003_SubstitutionTypeBase }
     * 
     */
    public P003_SubstitutionTypeBase createP003_SubstitutionTypeBase() {
        return new P003_SubstitutionTypeBase();
    }

    /**
     * Create an instance of {@link P003_TextBase }
     * 
     */
    public P003_TextBase createP003_TextBase() {
        return new P003_TextBase();
    }

    /**
     * Create an instance of {@link P003_ValueCodeBase }
     * 
     */
    public P003_ValueCodeBase createP003_ValueCodeBase() {
        return new P003_ValueCodeBase();
    }

    /**
     * Create an instance of {@link P003_ValueDateTimeBase }
     * 
     */
    public P003_ValueDateTimeBase createP003_ValueDateTimeBase() {
        return new P003_ValueDateTimeBase();
    }

    /**
     * Create an instance of {@link P003_ValueNomenclatureBase }
     * 
     */
    public P003_ValueNomenclatureBase createP003_ValueNomenclatureBase() {
        return new P003_ValueNomenclatureBase();
    }

    /**
     * Create an instance of {@link P003_ValueQuantityBase }
     * 
     */
    public P003_ValueQuantityBase createP003_ValueQuantityBase() {
        return new P003_ValueQuantityBase();
    }

    /**
     * Create an instance of {@link P003_ValueScaleBase }
     * 
     */
    public P003_ValueScaleBase createP003_ValueScaleBase() {
        return new P003_ValueScaleBase();
    }

    /**
     * Create an instance of {@link P003_ValueStringBase }
     * 
     */
    public P003_ValueStringBase createP003_ValueStringBase() {
        return new P003_ValueStringBase();
    }

    /**
     * Create an instance of {@link P003_ValueUnitBase }
     * 
     */
    public P003_ValueUnitBase createP003_ValueUnitBase() {
        return new P003_ValueUnitBase();
    }

    /**
     * Create an instance of {@link P003_VerificationCodeBase }
     * 
     */
    public P003_VerificationCodeBase createP003_VerificationCodeBase() {
        return new P003_VerificationCodeBase();
    }

    /**
     * Create an instance of {@link P003_WasSubstitutedBase }
     * 
     */
    public P003_WasSubstitutedBase createP003_WasSubstitutedBase() {
        return new P003_WasSubstitutedBase();
    }

    /**
     * Create an instance of {@link P003_WeightBase }
     * 
     */
    public P003_WeightBase createP003_WeightBase() {
        return new P003_WeightBase();
    }

    /**
     * Create an instance of {@link P003_WhenHandedOverBase }
     * 
     */
    public P003_WhenHandedOverBase createP003_WhenHandedOverBase() {
        return new P003_WhenHandedOverBase();
    }

    /**
     * Create an instance of {@link P003_WhenPreparedBase }
     * 
     */
    public P003_WhenPreparedBase createP003_WhenPreparedBase() {
        return new P003_WhenPreparedBase();
    }

    /**
     * Create an instance of {@link P003_AddressBase }
     * 
     */
    public P003_AddressBase createP003_AddressBase() {
        return new P003_AddressBase();
    }

    /**
     * Create an instance of {@link OriginalP003_MessageBase }
     * 
     */
    public OriginalP003_MessageBase createOriginalP003_MessageBase() {
        return new OriginalP003_MessageBase();
    }

    /**
     * Create an instance of {@link OriginalP003_ContentsBase }
     * 
     */
    public OriginalP003_ContentsBase createOriginalP003_ContentsBase() {
        return new OriginalP003_ContentsBase();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_ContentsBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "contents")
    public JAXBElement<P003_ContentsBase> createContents(P003_ContentsBase value) {
        return new JAXBElement<P003_ContentsBase>(_Contents_QNAME, P003_ContentsBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "signature")
    public JAXBElement<Object> createSignature(Object value) {
        return new JAXBElement<Object>(_Signature_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_MessageBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "message")
    public JAXBElement<P003_MessageBase> createMessage(P003_MessageBase value) {
        return new JAXBElement<P003_MessageBase>(_Message_QNAME, P003_MessageBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_NrnBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "nrnPrescription")
    public JAXBElement<P003_NrnBase> createNrnPrescription(P003_NrnBase value) {
        return new JAXBElement<P003_NrnBase>(_NrnPrescription_QNAME, P003_NrnBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_LrnBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "lrn")
    public JAXBElement<P003_LrnBase> createLrn(P003_LrnBase value) {
        return new JAXBElement<P003_LrnBase>(_Lrn_QNAME, P003_LrnBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_PmiBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "pmi")
    public JAXBElement<P003_PmiBase> createPmi(P003_PmiBase value) {
        return new JAXBElement<P003_PmiBase>(_Pmi_QNAME, P003_PmiBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_IdentifierTypeBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "identifierType")
    public JAXBElement<P003_IdentifierTypeBase> createIdentifierType(P003_IdentifierTypeBase value) {
        return new JAXBElement<P003_IdentifierTypeBase>(_IdentifierType_QNAME, P003_IdentifierTypeBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_IdentifierBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "identifier")
    public JAXBElement<P003_IdentifierBase> createIdentifier(P003_IdentifierBase value) {
        return new JAXBElement<P003_IdentifierBase>(_Identifier_QNAME, P003_IdentifierBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_BirthDateBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "birthDate")
    public JAXBElement<P003_BirthDateBase> createBirthDate(P003_BirthDateBase value) {
        return new JAXBElement<P003_BirthDateBase>(_BirthDate_QNAME, P003_BirthDateBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P003_HumanNameBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.his.bg", name = "name")
    public JAXBElement<P003_HumanNameBase> createName(P003_HumanNameBase value) {
        return new JAXBElement<P003_HumanNameBase>(_Name_QNAME, P003_HumanNameBase.class, null, value);
    }

}
