//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p003;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CL016.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CL016"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="EC"/&gt;
 *     &lt;enumeration value="BC"/&gt;
 *     &lt;enumeration value="G"/&gt;
 *     &lt;enumeration value="TE"/&gt;
 *     &lt;enumeration value="TB"/&gt;
 *     &lt;enumeration value="TG"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CL016")
@XmlEnum
public enum P003_CL016 {

    E,
    EC,
    BC,
    G,
    TE,
    TB,
    TG,
    F,
    N;

    public String value() {
        return name();
    }

    public static P003_CL016 fromValue(String v) {
        return valueOf(v);
    }

}
