//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.24 at 06:36:48 PM EET 
//


package com.ibm.eprescription.model.p003;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contentsBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contentsBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{https://www.his.bg}contentsBase"&gt;
 *       &lt;redefine&gt;
 *         &lt;complexType name="contentsBase"&gt;
 *           &lt;complexContent&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *               &lt;sequence&gt;
 *               &lt;/sequence&gt;
 *             &lt;/restriction&gt;
 *           &lt;/complexContent&gt;
 *         &lt;/complexType&gt;
 *       &lt;/redefine&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://www.his.bg}nrnPrescription" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}lrn" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}pmi" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}identifierType" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}identifier" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}birthDate" minOccurs="0"/&gt;
 *         &lt;element ref="{https://www.his.bg}name" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contentsBase", propOrder = {
    "nrnPrescription",
    "lrn",
    "pmi",
    "identifierType",
    "identifier",
    "birthDate",
    "name"
})
public class P003_ContentsBase
    extends OriginalP003_ContentsBase
{

    protected P003_NrnBase nrnPrescription;
    protected P003_LrnBase lrn;
    protected P003_PmiBase pmi;
    protected P003_IdentifierTypeBase identifierType;
    protected P003_IdentifierBase identifier;
    protected P003_BirthDateBase birthDate;
    protected P003_HumanNameBase name;

    /**
     * Gets the value of the nrnPrescription property.
     * 
     * @return
     *     possible object is
     *     {@link P003_NrnBase }
     *     
     */
    public P003_NrnBase getNrnPrescription() {
        return nrnPrescription;
    }

    /**
     * Sets the value of the nrnPrescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link P003_NrnBase }
     *     
     */
    public void setNrnPrescription(P003_NrnBase value) {
        this.nrnPrescription = value;
    }

    /**
     * Gets the value of the lrn property.
     * 
     * @return
     *     possible object is
     *     {@link P003_LrnBase }
     *     
     */
    public P003_LrnBase getLrn() {
        return lrn;
    }

    /**
     * Sets the value of the lrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link P003_LrnBase }
     *     
     */
    public void setLrn(P003_LrnBase value) {
        this.lrn = value;
    }

    /**
     * Gets the value of the pmi property.
     * 
     * @return
     *     possible object is
     *     {@link P003_PmiBase }
     *     
     */
    public P003_PmiBase getPmi() {
        return pmi;
    }

    /**
     * Sets the value of the pmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link P003_PmiBase }
     *     
     */
    public void setPmi(P003_PmiBase value) {
        this.pmi = value;
    }

    /**
     * Gets the value of the identifierType property.
     * 
     * @return
     *     possible object is
     *     {@link P003_IdentifierTypeBase }
     *     
     */
    public P003_IdentifierTypeBase getIdentifierType() {
        return identifierType;
    }

    /**
     * Sets the value of the identifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link P003_IdentifierTypeBase }
     *     
     */
    public void setIdentifierType(P003_IdentifierTypeBase value) {
        this.identifierType = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link P003_IdentifierBase }
     *     
     */
    public P003_IdentifierBase getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link P003_IdentifierBase }
     *     
     */
    public void setIdentifier(P003_IdentifierBase value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link P003_BirthDateBase }
     *     
     */
    public P003_BirthDateBase getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link P003_BirthDateBase }
     *     
     */
    public void setBirthDate(P003_BirthDateBase value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link P003_HumanNameBase }
     *     
     */
    public P003_HumanNameBase getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link P003_HumanNameBase }
     *     
     */
    public void setName(P003_HumanNameBase value) {
        this.name = value;
    }

}
